language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

# install dependencies
install: 
  -pip install -r requirements.txt

deploy:
  provider: gae
  keyfile: client-secret.json
  project: cisc3140

